let a;
a = 1;
switch (a) {
    case 0: console.log(a);
        ++a;
    case 1: console.log(a);
        ++a;
    case 2: console.log(a);
        ++a;
    case 3: console.log(a);
        ++a;
    case 4: console.log(a);
        ++a;
    case 5: console.log(a);
        ++a;
    case 6: console.log(a);
        ++a;
    case 7: console.log(a);
        ++a;
    case 8: console.log(a);
        ++a;
    case 9: console.log(a);
        ++a;
    case 10: console.log(a);
        ++a;
    case 11: console.log(a);
        ++a;
    case 12: console.log(a);
        ++a;
    case 13: console.log(a);
        ++a;
    case 14: console.log(a);
        ++a;
    case 15: console.log(a);
        break;
    default: console.log('Переменной а присвоено неверное значение.')
};